### ISSUE TITLE
Scripts for training and testing on RLBench_18tasks

### ISSUE THREAD

**Issue by hwh23** [vlc-robot/robot-3dlotus#2]
Hello,  Thank you for your excellent work! Could you please provide the scripts for training and testing on RLBench_18tasks, as well as any available checkpoints?  Best regards！

**Comment by cshizhe** [comment]
Please see [here](https://github.com/vlc-robot/robot-3dlotus/blob/main/README.md#training-and-evaluation-on-rlbench-18task-dataset-peract) for the scripts and trained model on RLBench_18tasks benchmark.
