### ISSUE TITLE
scripts for preprocessing peract training dataset

### ISSUE THREAD

**Issue by FinnJob** [vlc-robot/robot-3dlotus#3]
Thank you for your excellent work! Could you please provide the scripts for preprocessing peract training dataset?

**Comment by cshizhe** [comment]
We provided the processed peract training dataset [here](https://github.com/vlc-robot/robot-3dlotus/blob/main/README.md#dataset). We will clean the preprocessing scripts and release them soon.

**Comment by FinnJob** [comment]
Thanks！

**Comment by cshizhe** [comment]
The scripts for data generation can be found [here](https://github.com/vlc-robot/robot-3dlotus/blob/main/DATAGEN.md).

**Comment by FinnJob** [comment]
@cshizhe Thanks!
